services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - ollama-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: chat-backend
    ports:
      - "3001:3001"
    depends_on:
      - ollama
    networks:
      - ollama-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ollama-network
    restart: unless-stopped

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama_data:
